/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package goclient

// PatchQueryCommentInQueryHistoryCommand is the command for updating comment for query in query history
type PatchQueryCommentInQueryHistoryCommandModel struct {
	// Updated comment
	Comment string `json:"comment,omitempty"`
}
