/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package goclient

// Threshold a single step on the threshold list
type ThresholdModel struct {
	Color string            `json:"color,omitempty"`
	State string            `json:"state,omitempty"`
	Value *ConfFloat64Model `json:"value,omitempty"`
}
