/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package goclient

// Each Field is well typed by its FieldType and supports optional Labels.  A Frame is a general data container for Grafana. A Frame can be table data or time series data depending on its content and field types.
type FrameModel struct {
	// Fields are the columns of a frame. All Fields must be of the same the length when marshalling the Frame for transmission.
	Fields []FieldModel    `json:"Fields,omitempty"`
	Meta   *FrameMetaModel `json:"Meta,omitempty"`
	// Name is used in some Grafana visualizations.
	Name string `json:"Name,omitempty"`
	// RefID is a property that can be set to match a Frame to its originating query.
	RefID string `json:"RefID,omitempty"`
}
