/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package goclient

type NoticeModel struct {
	Inspect *InspectTypeModel `json:"inspect,omitempty"`
	// Link is an optional link for display in the user interface and can be an absolute URL or a path relative to Grafana's root url.
	Link     string               `json:"link,omitempty"`
	Severity *NoticeSeverityModel `json:"severity,omitempty"`
	// Text is freeform descriptive text for the notice.
	Text string `json:"text,omitempty"`
}
